### PR TITLE
Update `vue-function-api` to `@vue/composition-api`

### PR DESCRIPTION
**Pull request by kidonng**
Love your fun game! ❤

- The package `vue-function-api` has been renamed, update it
- Add some types
- Remove unused imports
- ~~(**Opinionated**) "Show hints?" can't be toggled off and is reset every round
  Because I simply can't stop cheating 🤣~~ #3

### CODE REVIEW

**Comment by ycmjason** [comment]
Thanks for the PR! 🎉 

I have done the same about updating to `@vue/composition-api` but Vetur is not picking up the types correctly in the templates. Will check later on my VSCode. 

Thanks a lot!

**Comment by ycmjason** [comment]
@kidonng 
I have fixed some issues about `RequiredProp` hack. Can you please update your upstream?

Also, I have tried out your branch and looks like Vetur is still complaining. I will wait till the `@vue/composition-api` working with Vetur before merging this.

I like your idea about "show hints". Can you put that into another PR so that it will not be blocked by this?

**Comment by ycmjason** [comment]
@kidonng I have done the fixing for you. Can you confirm that Vetur is breaking on your side too if you use VSCode?

**Comment by kidonng** [comment]
> I like your idea about "show hints". Can you put that into another PR so that it will not be blocked by this?

Sure!

**Comment by ycmjason** [comment]
@kidonng thank you very much.

Have you tried this branch on VSCode + Vetur? Can it show the types in the templates correctly on your machine?

**Comment by kidonng** [comment]
> Have you tried this branch on VSCode + Vetur? Can it show the types in the templates correctly on your machine?


Sorry, I was dealing with another repo just now. This PR is made with WebStorm, and I just checked it with VS Code, I guess it's fine...

image

**Comment by kidonng** [comment]
@ycmjason 

```js
export default createComponent<{
  difficulty: number, // These types are for `@vue/composition-api`
  showHint: boolean, // See https://github.com/vuejs/composition-api/releases/tag/v0.2.1
}>({
  components: { RangeInputWithDisplay, ColorRect },
  props: {
    difficulty: Number,
    showHint: Boolean,
  }
```

With these types added:

image

**Pull request closed without merging**
